fpath=(~/dotfiles/zsh/completion $fpath)

# get auto completes going
autoload -U compinit
compinit

source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions
source $HOME/dotfiles/zsh/prompt
source $HOME/dotfiles/zsh/secret


HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000


setopt auto_cd
